# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prises',
            name='good_price',
            field=models.IntegerField(default=0, verbose_name='price'),
            preserve_default=False,
        ),
    ]
