# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0002_prises_good_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='prises',
            name='pic',
            field=models.ImageField(default=100, upload_to='/shop/'),
            preserve_default=False,
        ),
    ]
