# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0003_prises_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prises',
            name='pic',
            field=models.ImageField(upload_to='shop/'),
        ),
    ]
