# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0004_auto_20160502_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prises',
            name='good_about',
            field=models.TextField(),
        ),
    ]
