# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-07 18:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0006_auto_20160504_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slag_url',
            field=models.SlugField(default=datetime.datetime(2016, 5, 7, 18, 5, 35, 60737, tzinfo=utc), help_text='якщо все вийде- то це буде ссиль', max_length=42),
            preserve_default=False,
        ),
    ]
