# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0007_category_slag_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='prises',
            name='in_magaz',
            field=models.BooleanField(db_index=True, default=True, help_text='наличие товара на складе'),
        ),
    ]
