# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-22 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0008_prises_in_magaz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prises',
            name='good_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
