# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 17:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_day',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 6, 17, 53, 13, 482722, tzinfo=utc), verbose_name='pub date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(),
        ),
    ]
