# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 18:35
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160406_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=redactor.fields.RedactorField(verbose_name='Text'),
        ),
    ]
