# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160525_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PartrerName', models.CharField(max_length=40)),
                ('PartnerPic', models.ImageField(upload_to='partners/')),
                ('PartnerDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-PartnerDate'],
            },
        ),
    ]
