# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_partners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partners',
            old_name='PartrerName',
            new_name='PartnerName',
        ),
    ]
